var ALIASES = {};
ALIASES["interledger_http"] = {};
ALIASES["interledger_ildcp"] = {};
ALIASES["interledger_packet"] = {};
ALIASES["interledger_router"] = {};
ALIASES["interledger_service"] = {};
ALIASES["interledger_service_util"] = {};
ALIASES["interledger_settlement"] = {};
ALIASES["interledger_stream"] = {};
