(function() {var implementors = {};
implementors["interledger_settlement"] = [{text:"impl&lt;__U, S, O, A&gt; <a class=\"trait\" href=\"https://docs.rs/tower-web/0.3.7/tower_web/util/chain/trait.Chain.html\" title=\"trait tower_web::util::chain::Chain\">Chain</a>&lt;__U&gt; for <a class=\"struct\" href=\"interledger_settlement/struct.SettlementApi.html\" title=\"struct interledger_settlement::SettlementApi\">SettlementApi</a>&lt;S, O, A&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;S: <a class=\"trait\" href=\"interledger_settlement/trait.SettlementStore.html\" title=\"trait interledger_settlement::SettlementStore\">SettlementStore</a>&lt;Account = A&gt; + <a class=\"trait\" href=\"interledger_settlement/trait.IdempotentStore.html\" title=\"trait interledger_settlement::IdempotentStore\">IdempotentStore</a> + <a class=\"trait\" href=\"interledger_service/trait.AccountStore.html\" title=\"trait interledger_service::AccountStore\">AccountStore</a>&lt;Account = A&gt; + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> + 'static,<br>&nbsp;&nbsp;&nbsp;&nbsp;O: <a class=\"trait\" href=\"interledger_service/trait.OutgoingService.html\" title=\"trait interledger_service::OutgoingService\">OutgoingService</a>&lt;A&gt; + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> + 'static,<br>&nbsp;&nbsp;&nbsp;&nbsp;A: <a class=\"trait\" href=\"interledger_settlement/trait.SettlementAccount.html\" title=\"trait interledger_settlement::SettlementAccount\">SettlementAccount</a> + <a class=\"trait\" href=\"interledger_ildcp/trait.IldcpAccount.html\" title=\"trait interledger_ildcp::IldcpAccount\">IldcpAccount</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> + 'static,&nbsp;</span>",synthetic:false,types:["interledger_settlement::api::SettlementApi"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
